name: Interact with Google Drive
description: Upload/Download files to/from Google Drive

branding:
  icon: upload-cloud
  color: 'gray-dark'

inputs:
  client-secret:
    description: 'client secret file body'
    required: true

  download-file-id:
    description: "the id to download file"
    required: false

  download-path:
    description: "The path where the files to be downloaded is located"
    required: false
    default: ./

runs:
  using: docker
  image: Dockerfile
  env:
   CLIENT_SECRET: ${{ inputs.client-secret }}
   DOWNLOAD_FILE_ID: ${{ inputs.download-file-id }}
   DOWNLOAD_PATH: ${{ inputs.download-path }}
   
